"""Read/write HEC-RAS HDF5 output files."""

from ._geometry import (
    BoundaryConditionCollection,
    BoundaryConditionLine,
    HdfBridge,
    FlowArea,
    FlowAreaCollection,
    HdfGateGroup,
    GeometryHdf,
    HdfCrossSection,
    HdfCrossSectionCollection,
    HdfGateOpening,
    HdfInline,
    HdfLateral,
    SA2DConnection,
    StorageArea,
    StorageAreaCollection,
    HdfStructure,
    HdfStructureCollection,
    HdfStructureIndex,
    HdfWeir,
)

# Backward-compatible aliases (deprecated — use Hdf-prefixed names)
CrossSection = HdfCrossSection
CrossSectionCollection = HdfCrossSectionCollection
GateOpening = HdfGateOpening
from ._steady_plan import (
    CrossSectionResults as SteadyCrossSectionResults,
    CrossSectionResultsCollection as SteadyCrossSectionResultsCollection,
    LateralResults as SteadyLateralResults,
    SteadyPlanHdf,
    StorageAreaResults as SteadyStorageAreaResults,
    StorageAreaResultsCollection as SteadyStorageAreaResultsCollection,
    StructureCollection as SteadyStructureCollection,
)
from ._unsteady_plan import (
    BridgeResults,
    FlowAreaResults,
    FlowAreaResultsCollection,
    InlineResults,
    LateralResults,
    SA2DConnectionResults,
    StorageAreaResults,
    StorageAreaResultsCollection,
    CrossSectionResults as UnsteadyCrossSectionResults,
    CrossSectionResultsCollection as UnsteadyCrossSectionResultsCollection,
    CrossSectionResultsDss as UnsteadyCrossSectionResultsDss,
    CrossSectionResultsInst as UnsteadyCrossSectionResultsInst,
    UnsteadyPlanHdf,
)

__all__ = [
    "GeometryHdf",
    "SteadyPlanHdf",
    "SteadyCrossSectionResults",
    "SteadyCrossSectionResultsCollection",
    "SteadyLateralResults",
    "SteadyStorageAreaResults",
    "SteadyStorageAreaResultsCollection",
    "SteadyStructureCollection",
    "UnsteadyPlanHdf",
    # HDF geometry classes
    "HdfCrossSection",
    "HdfCrossSectionCollection",
    "HdfGateOpening",
    "HdfBridge",
    "HdfInline",
    "HdfLateral",
    "HdfStructure",
    "HdfStructureIndex",
    "HdfWeir",
    "HdfGateGroup",
    # Unsteady results classes
    "UnsteadyCrossSectionResults",
    "UnsteadyCrossSectionResultsDss",
    "UnsteadyCrossSectionResultsInst",
    "UnsteadyCrossSectionResultsCollection",
    "FlowAreaCollection",
    "FlowAreaResultsCollection",
    "FlowArea",
    "FlowAreaResults",
    "StorageArea",
    "StorageAreaCollection",
    "StorageAreaResults",
    "StorageAreaResultsCollection",
    "SA2DConnectionResults",
    "BridgeResults",
    "InlineResults",
    "LateralResults",
    "BoundaryConditionLine",
    "BoundaryConditionCollection",
    "SA2DConnection",
    "HdfStructureCollection",
    # Backward-compatible aliases
    "CrossSection",
    "CrossSectionCollection",
    "GateOpening",
]
