"""Read/write HEC-RAS HDF5 output files."""

from ._geometry import (
    BoundaryConditionCollection,
    BoundaryConditionLine,
    Bridge,
    FlowArea,
    FlowAreaCollection,
    GateGroup,
    Geometry,
    CrossSection,
    CrossSectionCollection,
    GateOpening,
    InlineStructure,
    LateralStructure,
    SA2DConnection,
    StorageArea,
    StorageAreaCollection,
    Structure,
    StructureCollection,
    StructureIndex,
    Weir,
)
from ._steady_plan import (
    CrossSectionResults as SteadyCrossSectionResults,
    CrossSectionResultsCollection as SteadyCrossSectionResultsCollection,
    LateralResults as SteadyLateralResults,
    SteadyPlan,
    StorageAreaResults as SteadyStorageAreaResults,
    StorageAreaResultsCollection as SteadyStorageAreaResultsCollection,
    StructureResultsCollection as SteadyStructureResultsCollection,
)
from ._unsteady_plan import (
    BridgeResults,
    FlowAreaResults,
    FlowAreaResultsCollection,
    InlineResults,
    LateralResults,
    SA2DConnectionResults,
    StorageAreaResults,
    StorageAreaResultsCollection,
    CrossSectionResults as UnsteadyCrossSectionResults,
    CrossSectionResultsCollection as UnsteadyCrossSectionResultsCollection,
    CrossSectionResultsDSS as UnsteadyCrossSectionResultsDSS,
    CrossSectionResultsInstantaneous as UnsteadyCrossSectionResultsInstantaneous,
    UnsteadyPlan,
)

__all__ = [
    "Geometry",
    "SteadyPlan",
    "SteadyCrossSectionResults",
    "SteadyCrossSectionResultsCollection",
    "SteadyLateralResults",
    "SteadyStorageAreaResults",
    "SteadyStorageAreaResultsCollection",
    "SteadyStructureResultsCollection",
    "UnsteadyPlan",
    # HDF geometry classes
    "CrossSection",
    "CrossSectionCollection",
    "GateOpening",
    "Bridge",
    "InlineStructure",
    "LateralStructure",
    "Structure",
    "StructureIndex",
    "Weir",
    "GateGroup",
    # Unsteady results classes
    "UnsteadyCrossSectionResults",
    "UnsteadyCrossSectionResultsDSS",
    "UnsteadyCrossSectionResultsInstantaneous",
    "UnsteadyCrossSectionResultsCollection",
    "FlowAreaCollection",
    "FlowAreaResultsCollection",
    "FlowArea",
    "FlowAreaResults",
    "StorageArea",
    "StorageAreaCollection",
    "StorageAreaResults",
    "StorageAreaResultsCollection",
    "SA2DConnectionResults",
    "BridgeResults",
    "InlineResults",
    "LateralResults",
    "BoundaryConditionLine",
    "BoundaryConditionCollection",
    "SA2DConnection",
    "StructureCollection",
    "StructureResultsCollection",
]
